1. Create a 1D NumPy array of integers from 0 to 9.

In [ ]:
#1D Numpy array of integers 0 to 9
import numpy as np
list = (0,1,2,3,4,5,6,7,8,9)
array_1d = np.array(list)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


2. Generate a 4x4 NumPy array filled with random integers between 0 and 100

In [ ]:
#Generating 4x4 array NumPy array
import numpy as np
random_array = np.random.randint(0, 100, size=(4, 4))
print(random_array)

[[86 89 92 14]
 [38 51 26 19]
 [83  1 94 15]
 [46 24  9 27]]


3. Given a NumPy array arr = np.arange(20).reshape(4, 5), extract the subarray containing the elements from the 2nd row and 2nd to 4th columns.

In [2]:
import numpy as np
arr = np.arange(20).reshape(4, 5)
print(arr)
subarray = arr[1, 1:4]
print(subarray)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[6 7 8]


4. Create a 3x3 identity matrix using NumPy.

In [ ]:
#Creating 3X3 identity matrix
import numpy as np
matrix = np.identity(3)
print("The 3X3 identity matrix is:")
print(matrix)

The 3X3 identity matrix is:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


5. Generate a random 2x3 array of floats between 0 and 1.

In [ ]:
#Generating 2x3 NumPy array of floats 0 to 1
import numpy as np
random_array = np.random.rand(2, 3)
rounded_array = np.round(random_array, 3)
print(rounded_array)

[[0.872 0.295 0.471]
 [0.626 0.254 0.917]]


6. Reshape the array from question 5 into a 3x2 array.

In [ ]:
#Generating 3X2 NumPy array of floats 0 to 1
import numpy as np
random_array = np.random.rand(3, 2)
rounded_array = np.round(random_array, 3)
print(rounded_array)

[[0.62  0.16 ]
 [0.743 0.891]
 [0.966 0.037]]


7. Generate a 5x5 NumPy array filled with random floats between 0 and 1.

In [ ]:
#Generating 5x5 NumPy array of floats 0 to 1
import numpy as np
random_array = np.random.rand(5, 5)
rounded_array = np.round(random_array, 3)
print(rounded_array)

[[0.626 0.971 0.359 0.324 0.294]
 [0.698 0.046 0.769 0.187 0.416]
 [0.89  0.474 0.813 0.87  0.153]
 [0.266 0.16  0.946 0.842 0.63 ]
 [0.129 0.011 0.652 0.53  0.45 ]]


8. Reshape a 1D array of integers from 1 to 12 into a 3x4 matrix.

In [ ]:
#Reshaping 1D Array
import numpy as np
arr_1d = np.arange(1, 13)
arr_2d = arr_1d.reshape((3, 4))
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


9. Flatten a 2D array of shape (2, 3) into a 1D array.

In [3]:
#Flatten a 2D array to 1D array
import numpy as np
array = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Initial array: ", str(array))
final_array = array.flatten()
print("The new array is: ", final_array)

Initial array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
The new array is:  [1 2 3 4 5 6 7 8 9]


10.Convert a 1D array of 9 elements into a 3x3 square matrix.

In [14]:
#Converting 1d array of 9 elements in 3X3 matrix
import numpy as np
array = np.arange(9)
print("The array is: ", array)
matrix = array.reshape((3,3))
print("The matrix is: ")
print(matrix)

The array is:  [0 1 2 3 4 5 6 7 8]
The matrix is: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


11. Reshape a 1D array of 20 elements into a 4x5 matrix.

In [13]:
#Reshaping a 1D array of 20 elements into 4X5 matrix
import numpy as np
array = np.arange(20)
print("The array is: ", array)
matrix = array.reshape((4,5))
print("The matrix is: ")
print(matrix)

The array is:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
The matrix is: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


12.Concatenate the arrays [[1, 2, 3], [4, 5, 6]] and [[7, 8, 9], [10, 11, 12]] along the axis=0.

In [15]:
#Concatenate the arrays
import numpy as np
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
concatenated_array = np.concatenate((array1, array2), axis=0)
print(concatenated_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


13.Create a 2D NumPy array with shape (3, 3) filled with zeros.

In [16]:
#Creating 2D Numpy array with shape (3,3) filled with zero
import numpy as np
zero_array = np.zeros((3, 3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


14.Concatenate the arrays [[1, 2], [3, 4]] and [[5, 6], [7, 8]] along the second axis.

In [20]:
#Concatenate the arrays
import numpy as np
array1 = np.array([[1, 2], [3,4]])
array2 = np.array([[5,6], [7,8]])
concatenated_array = np.concatenate((array1, array2), axis=1)
print(concatenated_array)

[[1 2 5 6]
 [3 4 7 8]]


15. Transform a 2D array of shape (3, 2) into a 1D array of shape (6)

In [21]:
#transforming a 2D array
import numpy as np
arr = np.array([[1, 2], [3, 4] , [5,6]])
print(arr)
newarr = arr.reshape(-1)
print(" ")
print(newarr)

[[1 2]
 [3 4]
 [5 6]]
 
[1 2 3 4 5 6]
